In [1]:
import pandas as pd
import json

In [2]:
df_empresa_socio = pd.read_csv("empresa_socio.csv", sep=";")

In [3]:
print(df_empresa_socio.shape)
df_empresa_socio.head()

(506561, 5)

,ID_FORNECEDOR,NO_FORNECEDOR,ID_FORNECEDOR_PROPRIETARIO,TP_VINCULO_FORNECEDOR,SOCIO
0,191,BANCO DO BRASIL SA,1,1,2.079161e+10
1,191,BANCO DO BRASIL SA,1,1,1.106539e+10
2,191,BANCO DO BRASIL SA,1,1,4.552615e+10
3,191,BANCO DO BRASIL SA,1,1,8.803901e+10
4,191,BANCO DO BRASIL SA,1,1,4.579236e+10

In [4]:
df_bb = df_empresa_socio.loc[df_empresa_socio.ID_FORNECEDOR==191]
df_bb.shape

(37, 5)

In [5]:
df_socio = pd.read_csv("Socio.csv", sep=";")

In [6]:
print(df_socio.shape)
df_socio.head()

(1390854, 7)

,SOCIO,ID_SOCIO,NO_SOCIO,PAI_SOCIO,GRUPO,TP_SOCIO,NUM_PARTICIPACAO_ACIONARIA
0,191.0,191.0,BANCO DO BRASIL SA,183888.0,Sócio,2,"99,97"
1,191.0,191.0,BANCO DO BRASIL SA,183889.0,Sócio,2,"99,36"
2,191.0,191.0,BANCO DO BRASIL SA,183890.0,Sócio,2,"99,224641"
3,191.0,191.0,BANCO DO BRASIL SA,183891.0,Sócio,2,"99,237947"
4,191.0,191.0,BANCO DO BRASIL SA,183892.0,Sócio,2,"99,000034"

In [7]:
df_socio.loc[df_socio.ID_SOCIO==11065391846]

,SOCIO,ID_SOCIO,NO_SOCIO,PAI_SOCIO,GRUPO,TP_SOCIO,NUM_PARTICIPACAO_ACIONARIA
508964,1.106539e+10,1.106539e+10,MARCOS RENATO COLTRI,1.0,Sócio,1,NaN

### Prepara para o join

In [8]:
df_socio.SOCIO = df_socio.ID_SOCIO

### remove duplicados

In [9]:
df_socio = df_socio.drop_duplicates(subset='NO_SOCIO', keep="last")

In [10]:
df_joined = pd.merge(df_bb, df_socio, on=['SOCIO'],how='inner')

In [11]:
#df_join = df_bb.set_index('SOCIO').join(df_socio.set_index('ID_SOCIO'))

In [12]:
df_joined

,ID_FORNECEDOR,NO_FORNECEDOR,ID_FORNECEDOR_PROPRIETARIO,TP_VINCULO_FORNECEDOR,SOCIO,ID_SOCIO,NO_SOCIO,PAI_SOCIO,GRUPO,TP_SOCIO,NUM_PARTICIPACAO_ACIONARIA
0,191,BANCO DO BRASIL SA,1,1,2.079161e+10,2.079161e+10,JOSE EDUARDO PEREIRA FILHO,1.0,Sócio,1,NaN
1,191,BANCO DO BRASIL SA,1,1,1.106539e+10,1.106539e+10,MARCOS RENATO COLTRI,1.0,Sócio,1,NaN
2,191,BANCO DO BRASIL SA,1,1,4.552615e+10,4.552615e+10,JOSE RICARDO FAGONDE FORNI,1.0,Sócio,1,NaN
3,191,BANCO DO BRASIL SA,1,1,8.803901e+10,8.803901e+10,REINALDO KAZUFUMI YOKOYAMA,1.0,Sócio,1,NaN
4,191,BANCO DO BRASIL SA,1,1,4.579236e+10,4.579236e+10,MARCIO HAMILTON FERREIRA,174574.0,Dirigente,1,NaN
5,191,BANCO DO BRASIL SA,1,1,4.428873e+10,4.428873e+10,PAULO ROGERIO CAFFARELLI,195136.0,Sócio,1,NaN
6,191,BANCO DO BRASIL SA,1,1,5.632381e+10,5.632381e+10,MARCELO AUGUSTO DUTRA LABUTO,195136.0,Sócio,1,NaN
7,191,BANCO DO BRASIL SA,1,1,8.503562e+09,8.503562e+09,ROGERIO MAGNO PANCA,1.0,Sócio,1,NaN
8,191,BANCO DO BRASIL SA,1,1,1.563703e+10,1.563703e+10,ANTONIO GUSTAVO MATOS DO VALE,3529.0,Dirigente,1,NaN
9,191,BANCO DO BRASIL SA,1,1,6.694352e+10,6.694352e+10,CICERO PRZENDSIUK,1.0,Sócio,1,NaN
10,191,BANCO DO BRASIL SA,1,1,5.177150e+10,5.177150e+10,SIMAO LUIZ KOVALSKI,1.0,Sócio,1,NaN
11,191,BANCO DO BRASIL SA,1,1,8.775559e+09,8.775559e+09,FERNANDO FLORENCIO CAMPOS,283973.0,Sócio,1,NaN
12,191,BANCO DO BRASIL SA,1,1,1.415907e+08,1.415907e+08,CARLOS ALBERTO ARAUJO NETTO,1.0,Sócio,1,NaN
13,191,BANCO DO BRASIL SA,1,1,4.536003e+10,4.536003e+10,TARCISIO HUBNER,1.0,Sócio,1,NaN
14,191,BANCO DO BRASIL SA,1,1,6.929839e+10,6.929839e+10,MARVIO MELO FREITAS,393641.0,Sócio,1,NaN
15,191,BANCO DO BRASIL SA,1,1,3.802288e+09,3.802288e+09,ANTONIO MAURICIO MAURANO,283973.0,Sócio,1,NaN
16,191,BANCO DO BRASIL SA,1,1,5.103093e+10,5.103093e+10,EDSON ROGERIO DA COSTA,1.0,Sócio,1,NaN
17,191,BANCO DO BRASIL SA,1,1,7.768906e+10,7.768906e+10,BERNARDO DE AZEVEDO SILVA ROTHE,1.0,Sócio,1,NaN
18,191,BANCO DO BRASIL SA,1,1,5.834914e+10,5.834914e+10,NILSON MARTINIANO MOREIRA,1.0,Sócio,1,NaN
19,191,BANCO DO BRASIL SA,1,1,9.817617e+10,9.817617e+10,LEONARDO SILVA DE LOYOLA REIS,1.0,Sócio,1,NaN
20,191,BANCO DO BRASIL SA,1,1,1.012959e+10,1.012959e+10,CARLA NESI,1.0,Sócio,1,NaN
21,191,BANCO DO BRASIL SA,1,1,9.219825e+09,9.219825e+09,CARLOS RENATO BONETTI,1.0,Sócio,1,NaN
22,191,BANCO DO BRASIL SA,1,1,9.781600e+10,9.781600e+10,GUSTAVO DE SOUZA FOSSE,393641.0,Sócio,1,NaN
23,191,BANCO DO BRASIL SA,1,1,4.876778e+10,4.876778e+10,MARCO TULIO MORAES DA COSTA,1.0,Sócio,1,NaN
24,191,BANCO DO BRASIL SA,1,1,5.749072e+10,5.749072e+10,JOSE CAETANO DE ANDRADE MINCHILLO,1.0,Sócio,1,NaN
25,191,BANCO DO BRASIL SA,1,1,5.410359e+10,5.410359e+10,EDUARDO CESAR PASA,1.0,Sócio,1,NaN
26,191,BANCO DO BRASIL SA,1,1,7.494033e+10,7.494033e+10,MARCO TULIO DE OLIVEIRA MENDONCA,1.0,Sócio,1,NaN
27,191,BANCO DO BRASIL SA,1,1,3.650457e+10,3.650457e+10,JOSE EDUARDO MOREIRA BERGO,1.0,Sócio,1,NaN
28,191,BANCO DO BRASIL SA,1,1,5.403092e+10,5.403092e+10,LUCINEIA POSSAR,1.0,Sócio,1,NaN
29,191,BANCO DO BRASIL SA,1,1,1.177185e+10,1.177185e+10,WALTER MALIENI JUNIOR,1.0,Sócio,1,NaN
30,191,BANCO DO BRASIL SA,1,1,6.285904e+09,6.285904e+09,MARCIO LUIZ MORAL,1.0,Sócio,1,NaN
31,191,BANCO DO BRASIL SA,1,1,5.038160e+10,5.038160e+10,FABIANO MACANHAN FONTES,1.0,Sócio,1,NaN
32,191,BANCO DO BRASIL SA,1,1,9.550931e+10,9.550931e+10,ALEXANDRE ALVES DE SOUZA,1.0,Sócio,1,NaN
33,191,BANCO DO BRASIL SA,1,1,3.643475e+10,3.643475e+10,JOAO PINTO RABELO JUNIOR,1.0,Sócio,1,NaN
34,191,BANCO DO BRASIL SA,1,1,2.237948e+10,2.237948e+10,CARLOS HAMILTON VASCONCELOS ARAUJO,1.0,Sócio,1,NaN
35,191,BANCO DO BRASIL SA,1,1,6.219813e+09,6.219813e+09,MARCO ANTONIO ASCOLI MASTROENI,1.0,Sócio,1,NaN

### Cria json

In [14]:
data = {}
data['nodes'] = [{
      "id": int(df_joined.ID_FORNECEDOR[0]),
      "name": df_joined.NO_FORNECEDOR[0],
      "group": 1
    }]

data['links'] = []

for index, row in df_joined.iterrows():
    data['nodes'].append({"id":int(row.SOCIO),"name":row.NO_SOCIO,"group":2})
    data['links'].append({"source":int(row.SOCIO),"target":int(df_joined.ID_FORNECEDOR[0])})

### preview para checar o arquivo

In [15]:
json_data = json.dumps(data)
json_data

'{"nodes": [{"id": 191, "name": "BANCO DO BRASIL SA", "group": 1}, {"id": 20791607372, "name": "JOSE EDUARDO PEREIRA FILHO", "group": 2}, {"id": 11065391846, "name": "MARCOS RENATO COLTRI", "group": 2}, {"id": 45526150178, "name": "JOSE RICARDO FAGONDE FORNI", "group": 2}, {"id": 88039005949, "name": "REINALDO KAZUFUMI YOKOYAMA", "group": 2}, {"id": 45792364168, "name": "MARCIO HAMILTON FERREIRA", "group": 2}, {"id": 44288727987, "name": "PAULO ROGERIO CAFFARELLI", "group": 2}, {"id": 56323808153, "name": "MARCELO AUGUSTO DUTRA LABUTO", "group": 2}, {"id": 8503561808, "name": "ROGERIO MAGNO PANCA", "group": 2}, {"id": 15637026653, "name": "ANTONIO GUSTAVO MATOS DO VALE", "group": 2}, {"id": 66943515934, "name": "CICERO PRZENDSIUK", "group": 2}, {"id": 51771497068, "name": "SIMAO LUIZ KOVALSKI", "group": 2}, {"id": 8775558858, "name": "FERNANDO FLORENCIO CAMPOS", "group": 2}, {"id": 141590742, "name": "CARLOS ALBERTO ARAUJO NETTO", "group": 2}, {"id": 45360030968, "name": "TARCISIO HUBNER", "group": 2}, {"id": 69298394187, "name": "MARVIO MELO FREITAS", "group": 2}, {"id": 3802287851, "name": "ANTONIO MAURICIO MAURANO", "group": 2}, {"id": 51030926034, "name": "EDSON ROGERIO DA COSTA", "group": 2}, {"id": 77689062768, "name": "BERNARDO DE AZEVEDO SILVA ROTHE", "group": 2}, {"id": 58349138653, "name": "NILSON MARTINIANO MOREIRA", "group": 2}, {"id": 98176170763, "name": "LEONARDO SILVA DE LOYOLA REIS", "group": 2}, {"id": 10129586803, "name": "CARLA NESI", "group": 2}, {"id": 9219824884, "name": "CARLOS RENATO BONETTI", "group": 2}, {"id": 97816000715, "name": "GUSTAVO DE SOUZA FOSSE", "group": 2}, {"id": 48767778615, "name": "MARCO TULIO MORAES DA COSTA", "group": 2}, {"id": 57490716691, "name": "JOSE CAETANO DE ANDRADE MINCHILLO", "group": 2}, {"id": 54103592087, "name": "EDUARDO CESAR PASA", "group": 2}, {"id": 74940333604, "name": "MARCO TULIO DE OLIVEIRA MENDONCA", "group": 2}, {"id": 36504572100, "name": "JOSE EDUARDO MOREIRA BERGO", "group": 2}, {"id": 54030919987, "name": "LUCINEIA POSSAR", "group": 2}, {"id": 11771846801, "name": "WALTER MALIENI JUNIOR", "group": 2}, {"id": 6285903859, "name": "MARCIO LUIZ MORAL", "group": 2}, {"id": 50381601900, "name": "FABIANO MACANHAN FONTES", "group": 2}, {"id": 95509305720, "name": "ALEXANDRE ALVES DE SOUZA", "group": 2}, {"id": 36434752172, "name": "JOAO PINTO RABELO JUNIOR", "group": 2}, {"id": 22379479372, "name": "CARLOS HAMILTON VASCONCELOS ARAUJO", "group": 2}, {"id": 6219812816, "name": "MARCO ANTONIO ASCOLI MASTROENI", "group": 2}], "links": [{"source": 20791607372, "target": 191}, {"source": 11065391846, "target": 191}, {"source": 45526150178, "target": 191}, {"source": 88039005949, "target": 191}, {"source": 45792364168, "target": 191}, {"source": 44288727987, "target": 191}, {"source": 56323808153, "target": 191}, {"source": 8503561808, "target": 191}, {"source": 15637026653, "target": 191}, {"source": 66943515934, "target": 191}, {"source": 51771497068, "target": 191}, {"source": 8775558858, "target": 191}, {"source": 141590742, "target": 191}, {"source": 45360030968, "target": 191}, {"source": 69298394187, "target": 191}, {"source": 3802287851, "target": 191}, {"source": 51030926034, "target": 191}, {"source": 77689062768, "target": 191}, {"source": 58349138653, "target": 191}, {"source": 98176170763, "target": 191}, {"source": 10129586803, "target": 191}, {"source": 9219824884, "target": 191}, {"source": 97816000715, "target": 191}, {"source": 48767778615, "target": 191}, {"source": 57490716691, "target": 191}, {"source": 54103592087, "target": 191}, {"source": 74940333604, "target": 191}, {"source": 36504572100, "target": 191}, {"source": 54030919987, "target": 191}, {"source": 11771846801, "target": 191}, {"source": 6285903859, "target": 191}, {"source": 50381601900, "target": 191}, {"source": 95509305720, "target": 191}, {"source": 36434752172, "target": 191}, {"source": 22379479372, "target": 191}, {"source": 6219812816, "target": 191}]}'

In [16]:
with open('data.json', 'w') as outfile:
    json.dump(data, outfile)